type: Bearer Authentication
describedBy:
    headers:
        Authorization:
            description: Токен
            type: string
            example: "bearer ucboG8yfWKsd7DljVHHJjGMl3t6UZAL0"
    responses: !include responses.raml
